/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Solo_Jonathon_with_laptop2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations, useHelper } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import {motion } from "framer-motion-3d"
import { useThree } from '@react-three/fiber'
import { PointLightHelper } from 'three'


export function Model_Env(props) {
  const {currentAnimation, section} = props
  const viewport = useThree()
  const group = useRef()
  const PersonModel = useRef()
  const ComputerEnv = useRef()
  const { nodes, materials, animations } = useGLTF('/Solo_Jonathon_with_laptop2.glb')
  const { actions } = useAnimations(animations, PersonModel)

  useFrame(() =>{
    
    
  })
  function Light() {
    const pLight = useRef()
    // useHelper(pLight, PointLightHelper, 0.5, "hotpink")
    return (
      <pointLight ref={pLight} position={[0.1, 1.45, -0.85]} color={'#090C25'} intensity={28} scale={0.2}/>

    )

  }

  return (
      <group name="Scene" ref={group} dispose={null} >
        <Light/>
        <group ref={ComputerEnv} >
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['The color purple']} position={[0, 0.608, -0.042]} scale={0.333} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['The color purple']} rotation={[0,Math.PI,0]} position={[0, 0.711, -0.65]} scale={0.426} />
        <mesh name="computer_0" geometry={nodes.computer_0.geometry} material={materials.Material} position={[-0.2, 1.153, -0.8]} rotation={[0, Math.PI * 1.5 , Math.PI/2]} scale={-0.016} />
        </group>
      </group>
  )
}

useGLTF.preload('/Solo_Jonathon_with_laptop2.glb')
